openapi: 3.0.3
info:
  title: stocks
  version: 0.0.1
  description: stocks
  contact:
    name: tiger
servers:
  - url: http://localhost
tags:
  - name: stocks
paths:
  /stocks:
    get:
      operationId: get_stocks
      tags:
        - stocks
      description: get stocks
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/stock"
    post:
      operationId: add_stocks
      tags:
        - stocks
      description: add stocks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                example: EMQQ
      responses:
        "200":
          description: OK
  /stocks/{stock_name}:
    delete:
      operationId: delete_stock
      tags:
        - stocks
      description: delete a stock
      parameters:
        - name: stock_name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
          content:
            text/plain:
              example: the stock {stock_name} was not found
components:
  schemas:
    stock:
      properties:
        symbol:
          type: string
          example: ARKG
        symbolId:
          type: string
          example: "7956433"